### ISSUE TITLE
python3.5.2 encoding error

### ISSUE THREAD

**Issue by istobran** [septs/bilibili-live-kit#5]
> --- Logging error ---
Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 88-91: ordinal not in range(128)
Call stack:
  File "/opt/python3.5/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/opt/python3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/python3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lzb/WorkingDir/bilibili-live-kit/bilibili_live_kit/plugins/live_room.py", line 70, in send_heart
    heart_status = live.send_heart()
  File "/home/lzb/WorkingDir/bilibili-live-kit/bilibili_live_kit/plugins/live_room.py", line 22, in send_heart
    self.logger.info('Open failed: %(msg)s', payload)
Message: 'Open failed: %(msg)s'
Arguments: {'code': -403, 'msg': '\u975e\u6cd5\u5fc3\u8df3', 'data': [1474968089, 1474968031]}
--- Logging error ---
Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 88-91: ordinal not in range(128)
Call stack:
  File "/opt/python3.5/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/opt/python3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/python3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lzb/WorkingDir/bilibili-live-kit/bilibili_live_kit/plugins/live_room.py", line 70, in send_heart
    heart_status = live.send_heart()
  File "/home/lzb/WorkingDir/bilibili-live-kit/bilibili_live_kit/plugins/live_room.py", line 22, in send_heart
    self.logger.info('Open failed: %(msg)s', payload)
Message: 'Open failed: %(msg)s'
Arguments: {'code': -403, 'msg': '\u975e\u6cd5\u5fc3\u8df3', 'data': [1474968089, 1474968031]}

在python3.5.2上面跑存在编码报错问题

**Comment by septs** [comment]
大概是我没有设置 [PEP-263](https://www.python.org/dev/peps/pep-0263/) 导致的
